/* ========================================================================== */
/* File: AMStartup.c - Final Project 
 *
 * Author: Janice Yip
 * Date: 05/16/2014
 *
 * Description: query URLs for certain words  
 * Commandline input: ./query [FILENAME] 
 * User Input: [QUERY_WORDS]
 * 
 * Example command input
 * $ ./query ~cs50/tse/indexer/cs_lvl3.dat ~cs50/tse/crawler/lvl3 
 * $ QUERY:> computer security privacy 
 * 
 * [FILENAME] -> ~cs50/tse/indexer/cs_lvl3.dat
 * Requirement: File with words and document ids and frequencies 
 * Usage: The query reads from this file to construct the inverted index. 
 * 
 * [FILE_DIRECTORY] -> ~cs50/tse/crawler/lvl3
 * Requirement: Valid directory with files numbered starting from 1; 
 * 		files must have URL, depth, then HTML
 * Usage: The query engine goes through the files it needs and prints the URLs
 * 
 * Output: A print out of URLs containing the desired words in ranked order 
 * 
 * Error conditions: See requirements for each commandline input above
 * 
 * Pseudocode:
 *     1.   
 *     2.  
 *     3.  
 *     4.  
 *     5.    
 *     6.  
 * 	   7.  
 *     8.  
 *     9.   
 */

/* ========================================================================== */
// ---------------- Open Issues

// ---------------- System includes e.g., <stdio.h>
#include <stdio.h>                           // printf
#include <curl/curl.h>                       // curl functionality
#include <sys/types.h> 
#include <sys/stat.h> 
#include <unistd.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>


// ---------------- Local includes  e.g., "file.h"
#include "amazing.h"


// ---------------- Constant definitions

// ---------------- Macro definitions


// ---------------- Structures/Types

// ---------------- Private variables

// ---------------- Private prototypes


/* =========================================================================== */
/*                                   main                                      */
/* =========================================================================== */

int main(int argc, char* argv[])
{

}



The startup script, AMStartup, can be a shell script or C program. It should be able to handle these parameters at a minimum:

-n nAvatars 
(int) the number of Avatars in the maze
-d Difficulty
(int) the difficulty level, on the scale 0 (easy) to 9 (excruciatingly difficult)
-h Hostname
(char *) the hostname of the server. Our server will be running on pierce.cs.dartmouth.edu .
Once AMStartup has validated the arguments, it will construct and send the AM_INIT message to the server. When the server responds with AM_INIT_OK, AMStartup recovers the MazePort from that reply.

Then AMStartup creates a new log file with the name Amazing_$USER_N_D.log, where $USER is the current userid, N is the value of nAvatars and D is the value of Difficulty. The first line of the file should contain $USER, the MazePort, and the date & time. For example, the following shell command would produce this first line:

echo $USER, 10829, `date` > $filename
where $filename is a variable containing the name of the log file. Alternatively, if your AMStartup is a C program, then you may find the time() and ctime() functions in time.h helpful.
Then AMStartup will start the N copies of the Avatar client (as threads or processes) with the parameters they will need:

AvatarId (an integer generated by AMStartup, starting at 0 and incremented by one for each subsequent Avatar started)
nAvatars (total number of Avatars)
Difficulty (difficulty of the maze)
IP address of the server
MazePort (as returned in the AM_INIT_OK message).
Filename of the log the Avatar should open for writing in append mode.
While validity checking of the parameters in the startup script (program) is appropriate (defensive programming!), the client program is not really meant to be run by people, so the start parameters can be simply positional and required. For example, if you use a shell script to start the main client program the line might look like this:

./amazing_client 0 3 2 129.170.212.235 10829 Amazing_3_2.log
Of course, if you would prefer to setup these parameters with "getopt" style switches, that's ok too.

If you wish to add additional parameters, please speak with your customers (the TA and/or the instructor) first.